---
title: "Curve Optimisation"
output:
  html_document:
    df_print: paged
---



```{r, echo=FALSE}
library(readxl)
library(tidyverse)
library(writexl)


data_in <- read_excel("C:/Users/lee.kennedy/OneDrive - ALS Limited/Documents/GitHub/Curve_Optimising/data/Ethanol_Run6.xlsx")

force_zero <- data_in$Force_Zero[1]
units <- data_in$Units[1]
analyte <- data_in$Analyte[1]
```

This is an investigation of the `r analyte` standard curve to see which grouping of standards is most appropriate to use.


```{r, echo=FALSE}
data_in <- data_in[,1:2]
data_in <- data_in %>% mutate(data_in, ID = row_number())
data_in$Units <- units
data_in <- data_in[,c(3,1,4,2)]
# data_in[,4] <- signif(data_in[,4],4)
data_in

```

The following table groups standards into Run Sets, based on their ID number.



```{r, echo=FALSE}
data_in <- data_in[,c(2,4)]

df <- data.frame(Run_set = as.character(),
                 Points = as.numeric(),
                 Slope = as.numeric(), 
                 Intercept = as.numeric(), 
                 R2 = as.numeric(),
                 SE = as.numeric(),
                 stringsAsFactors=FALSE) 


n <- nrow(data_in)
m=n-3

for(i in 1:m) {
   
        data_in2 <- data_in[c(i:n),]
        Points = as.numeric(nrow(data_in2))
        
        fit <- lm(data_in2$Reading~data_in2$Standard)
        fit_summary <- summary(fit)
        slope_fit <- fit_summary$coefficients[2]
        slope_intercept <- fit_summary$coefficients[1]
        R2_fit <- fit_summary$r.squared
        SE_fit <- fit_summary$sigma
        Run_Set = paste(i,"to",n)
      

df <- rbind(df, data.frame(Run_set = Run_Set, Points, Slope = round(slope_fit,4), Intercept = round(slope_intercept,4), R2 = round(R2_fit,4), SE = round(SE_fit,4)))
}

m=n-3

for(i in 1:m) {
        j=i+2
        data_in2 <- data_in[c(1:j),]
        Points = as.numeric(nrow(data_in2))
        
        fit <- lm(data_in2$Reading~data_in2$Standard)
        fit_summary <- summary(fit)
        slope_fit <- fit_summary$coefficients[2]
        slope_intercept <- fit_summary$coefficients[1]
        R2_fit <- fit_summary$r.squared
        SE_fit <- fit_summary$sigma
        Run_Set = paste("1 to",j)
        
        
        
        df <- rbind(df, data.frame(Run_set = Run_Set, Points, Slope = round(slope_fit,4), Intercept = round(slope_intercept,4), R2 = round(R2_fit,4), SE = round(SE_fit,4)))
        
}

df <- df %>% arrange(SE)
df$LOQ <- round(df$SE*10,2)

df
```

